### ISSUE TITLE
[BUG] Always on top glitched on first launch

### ISSUE THREAD

**Issue by Sakarias411** [Eve-PySpy/PySpy#9]
**Describe the bug**
The "Always on top" setting is not working when first starting the application.

**To Reproduce**
- Download PySpy on a fresh Windows install (or VM, or clear local cached files)
- Start PySpy, notice the "Always on top" is enabled by default but it's not working UNTIL you disable it, then reenable it again.

**Expected behavior**
- Always on top should work on the first launch if it's default enabled

**System Environment:**
 - OS: Windows 10
 - OS Version: 1803
 - PySpy Version 0.4

**Additional context**

**Comment by leonhess** [comment]
Is this still a Problem with the newest release of PySpy (0.5.2), @Sakarias411?
